### ISSUE TITLE
[Docker] failed to solve: process "/bin/sh -c docker-php-ext-install pdlib-master"

### ISSUE THREAD

**Issue by mbnoimi** [matiasdelellis/facerecognition#698]
I failed to create a new container deepening on the instructions mentioned in the [wiki page](https://github.com/matiasdelellis/facerecognition/wiki/Docker#extend-nextcloudapache)!

I always get this error message (tested on two different machines):

```
failed to deploy a stack: failed to solve: process "/bin/sh -c docker-php-ext-install pdlib-master" did not complete successfully: exit code: 2 
```

May you please help me to find out what's wrong?

**docker-compose.yml**
```yml

version: '3'

services:
    postgresql:
        container_name: "test-postgresql"
        image: postgres:latest
        volumes:
            - /home/server/Storage/Congig_tmp/Postgresql/data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        restart: always
        environment:
            - POSTGRES_PASSWORD=346sdfddfg5SSD
            - POSTGRES_USER=root
            - POSTGRES_DB=postgres          
    nextcloud:
        container_name: "test-nextcloud"
        environment:
          - POSTGRES_PASSWORD=346sdfddfg5SSD
          - POSTGRES_DB=nextcloud
          - POSTGRES_USER=root
          - POSTGRES_HOST=postgresql
        # image: nextcloud:latest
        build: https://gist.githubusercontent.com/mbnoimi/6eda9e973959bb907007d09c23e84b43/raw/2808c90e049e6f0f232807721dd0a82176be36d3/nc.Dockerfile
        ports:
          - "80:80"
        restart: always
        volumes:
          - /home/server/Storage/Congig_tmp/Nextcloud/app:/var/www/html
        depends_on:
            - postgresql
```
